const states = [
  { label: 'Alabama', value: 'states/al' },
  { label: 'Alaska', value: 'states/ak' },
  { label: 'Arizona', value: 'states/az' },
  { label: 'Arkansas', value: 'states/ar' },
  { label: 'California', value: 'states/ca' },
  { label: 'Colorado', value: 'states/co' },
  { label: 'Connecticut', value: 'states/ct' },
  { label: 'Delaware', value: 'states/de' },
  { label: 'District Of Columbia', value: 'states/dc' },
  { label: 'Florida', value: 'states/fl' },
  { label: 'Georgia', value: 'states/ga' },
  { label: 'Guam', value: 'states/gu' },
  { label: 'Hawaii', value: 'states/hi' },
  { label: 'Idaho', value: 'states/id' },
  { label: 'Illinois', value: 'states/il' },
  { label: 'Indiana', value: 'states/in' },
  { label: 'Iowa', value: 'states/ia' },
  { label: 'Kansas', value: 'states/ks' },
  { label: 'Kentucky', value: 'states/ky' },
  { label: 'Louisiana', value: 'states/la' },
  { label: 'Maine', value: 'states/me' },
  { label: 'Maryland', value: 'states/md' },
  { label: 'Massachusetts', value: 'states/ma' },
  { label: 'Michigan', value: 'states/mi' },
  { label: 'Minnesota', value: 'states/mn' },
  { label: 'Mississippi', value: 'states/ms' },
  { label: 'Missouri', value: 'states/mo' },
  { label: 'Montana', value: 'states/mt' },
  { label: 'Nebraska', value: 'states/ne' },
  { label: 'Nevada', value: 'states/nv' },
  { label: 'New Hampshire', value: 'states/nh' },
  { label: 'New Jersey', value: 'states/nj' },
  { label: 'New Mexico', value: 'states/nm' },
  { label: 'New York', value: 'states/ny' },
  { label: 'North Carolina', value: 'states/nc' },
  { label: 'North Dakota', value: 'states/nd' },
  { label: 'Ohio', value: 'states/oh' },
  { label: 'Oklahoma', value: 'states/ok' },
  { label: 'Oregon', value: 'states/or' },
  { label: 'Pennsylvania', value: 'states/pa' },
  { label: 'Puerto Rico', value: 'states/pr' },
  { label: 'Rhode Island', value: 'states/ri' },
  { label: 'South Carolina', value: 'states/sc' },
  { label: 'South Dakota', value: 'states/sd' },
  { label: 'Tennessee', value: 'states/tn' },
  { label: 'Texas', value: 'states/tx' },
  { label: 'United States', value: 'us' },
  { label: 'Utah', value: 'states/ut' },
  { label: 'Vermont', value: 'states/vt' },
  { label: 'Virgin Islands', value: 'states/vi' },
  { label: 'Virginia', value: 'states/va' },
  { label: 'Washington', value: 'states/wa' },
  { label: 'West Virginia', value: 'states/wv' },
  { label: 'Wisconsin', value: 'states/wi' },
  { label: 'Wyoming', value: 'states/wy' },
]

export default states;